name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the deployable artifact files
                required: true
                default: dist
                type: string
        secrets:
            some-secret:
                description: Some description
                required: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - run: ls
            - run: "echo \"Deploying & uploading with secret: ${{ secrets.some-secret }}...\""