name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the deployable artifact files
                required: true
                default: dist
                type: string
        secrets:
            some-secret:
                description: Some description
                required: true
        outputs:
            result:
                description: Description of the otuput
                value: ${{ jobs.deploy.outputs.output-result }}

jobs:
    deploy:
        outputs:
            output-result: ${{ steps.set-output-result.outputs.step-output }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - run: ls
            - run: "echo \"Deploying & uploading with secret: ${{ secrets.some-secret }}...\""
            - id: set-output-result
              run: echo "step-output=success" >> $HITHUB_OUTPUT