name: Lint, Test, Build, Deploy Workflow
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch the repository
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run Lint
              run: npm run lint
            - name: Run Tests
              run: npm run test
    deploy:
        needs: test
        runs-on: ubuntu-lastest
        steps:
            - name: Fetch the repository
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Deploy
              run: echo "Deploy..."